direction: right

usuarios: {
  shape: sql_table
  id: int PK
  nombre: varchar(100)
  cedula: varchar(20) UNIQUE
  telefono: varchar(20)
  correo: varchar(100) UNIQUE
  password: varchar(255)
  seguro: varchar(50)
  rol: varchar(20)
  fecha_registro: timestamp
}

especialidades: {
  shape: sql_table
  id: int PK
  nombre: varchar(100)
  descripcion: text
  precio: decimal(10,2)
}

doctores: {
  shape: sql_table
  id: int PK
  nombre: varchar(100)
  id_especialidad: int FK
  id_usuario: int FK
}

citas: {
  shape: sql_table
  id: int PK
  id_usuario: int FK
  id_especialidad: int FK
  id_doctor: int FK
  fecha: date
  hora: time
  estado: enum
  fecha_creacion: timestamp
}

usuarios.id -> doctores.id_usuario: "1 a N"
especialidades.id -> doctores.id_especialidad: "1 a N"
usuarios.id -> citas.id_usuario: "1 a N"
especialidades.id -> citas.id_especialidad: "1 a N"
doctores.id -> citas.id_doctor: "1 a N"
